### ISSUE TITLE
Not able to run  the app

### ISSUE THREAD

**Issue by vatsal1812** [sachinbhatnagar/bankfresh-fsd-app#1]
I am not able to sign up in the app. Can you please help ?

**Comment by sachinbhatnagar** [comment]
Can you please share details of the issue you're facing? The signup should create an account in the database if configured correctly.

**Comment by sachinbhatnagar** [comment]
> I am not able to sign up in the app. Can you please help ?

Can you please share more details of the issue you're facing? Screenshots or error messages would help. The signup should create an account in the database if configured correctly.

**Comment by vatsal1812** [comment]
After clicking on signup it is showing the below  error on screen
![error](https://github.com/sachinbhatnagar/bankfresh-fsd-app/assets/60283110/66a16e80-61fd-41a2-80a2-d13398449d11)
Also it is showing the below errors in inspect console
![Uploading consoleError.png…]()

**Comment by sachinbhatnagar** [comment]
So this is where, you would need to dig in and examine the console to understand the exact error and also observe the code. This is an academic project intended for exploration and observation only and is not meant for professional use. 

Please note that if you're an upGrad learner, I would request you to raise a tech support ticket so support can be provided through TAs and official channels. If you're not a learner, feel free to dig in and explore the code.

However, as a quick note, check the browser console for possible issues to explore further. Hope this helps :)
